### ISSUE TITLE
Error occured while I running code on my video, some limits to video or misconfig enviorment?

### ISSUE THREAD

**Issue by fight-think** [senguptaumd/Background-Matting#34]
!CUDA_VISIBLE_DEVICES=0 python test_background-matting_image.py -m real-fixed-cam -i sample_video_fixed/input/ -o sample_video_fixed/output/ -tb sample_video_fixed/background/ -b sample_video_fixed/teaser_back.png

CUDA Device: 0
Using video mode
Traceback (most recent call last):
  File "test_background-matting_image.py", line 121, in <module>
    bbox=get_bbox(rcnn,R=bgr_img0.shape[0],C=bgr_img0.shape[1])
  File "/content/drive/My Drive/background_matting/Background-Matting/functions.py", line 38, in get_bbox
    x1, y1 = np.amin(where, axis=1)
  File "<__array_function__ internals>", line 6, in amin
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 2746, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by senguptaumd** [comment]
looks like segmentation might have failed and `rcnn` variable is empty.

**Comment by fight-think** [comment]
I get it, maybe I missed process of segmentation. I will try again. Thanks.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Soumyadip Sengupta"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月8日(星期五) 晚上6:45
收件人:&nbsp;"senguptaumd/Background-Matting"<Background-Matting@noreply.github.com&gt;;
抄送:&nbsp;"1297518605"<1297518605@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [senguptaumd/Background-Matting] Error occured while I running code on my video, some limits to video or misconfig enviorment? (#34)





 
looks like segmentation might have failed and rcnn variable is empty.

**Comment by somenewaccountthen** [comment]
Is it is because the frame is the same as the background, aka empty. And there is nothing to segment and code crashes coz can't handle that?
